
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    bash \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*

COPY script_bash.sh /script_bash.sh

RUN chmod +x /script_bash.sh

CMD ["/script_bash.sh"]

